# Book settings
title: ""
author: The Flatland Community
logo: assets/images/flatland-logo.svg

latex:
  latex_documents:
    targetname: book.tex

html:
  favicon: assets/images/favicon.ico
  google_analytics_id: UA-132885496-4
  home_page_in_navbar: true
  use_edit_page_button: false # will need custom gitlab integration

repository:
  url: https://gitlab.aicrowd.com/flatland/flatland-book

execute:
  execute_notebooks: off