apiVersion: apps/v1
kind: Deployment
metadata:
  name: flatland-docs
  namespace: flatland
  labels:
    app: flatland-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flatland-docs
  template:
    metadata:
      labels:
        app: flatland-docs
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: flatland-docs
        image: aicrowd/flatland-docs:$IMAGE_TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flatland-docs
  namespace: flatland
  labels:
    app: flatland-docs
spec:
  selector:
    app: flatland-docs
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: flatland-docs
  namespace: flatland
  labels:
    app: flatland-docs
spec:
  tls:
  - hosts:
      - flatland-docs.internal.k8s.aicrowd.com
    secretName: flatland-docs-tls-secret
  rules:
  - host: flatland-docs.internal.k8s.aicrowd.com
    http:
      paths:
      - path: /
        backend:
          serviceName: flatland-docs
          servicePort: 80
